# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists.

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy for the pre-processing tasks. Numpy arrays are represented in two forms: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (a matrix can still have only one row or one column).


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods
The built in functions are listed below

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2) 
#first argument = starting point
# second argument = ending point excluding it
# third argument = difference

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50,False,True)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
        2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
        5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
        7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]),
 0.2)

## eye

Creates an identity matrix

In [15]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Random number arrays can be generated in many ways

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [19]:
np.random.rand(2)

array([0.09459244, 0.27466137])

In [ ]:
np.random.rand(5,5)
#dimensions are not passed as tuple unlike in np.zeros()

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([0.79905815, 0.2412091 ])

In [21]:
np.random.randn(5,5)

array([[ 0.72116648, -0.96278049, -1.5869127 , -0.60660837, -0.70690827],
       [-0.29331552,  1.36085969, -0.20703628, -0.19353413,  0.5958938 ],
       [-0.06922728, -0.93332125, -1.07698404, -0.3712869 , -1.27262584],
       [-2.98858775,  0.84420607,  2.12297709, -0.93579937, -1.36920198],
       [-0.57060063, -1.04912116,  0.65120064, -1.20221611,  1.35383376]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

39

## Reshape
Returns an array containing the same data with a new shape.

In [23]:
arr=np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [24]:
arr = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39]) 

In [25]:
print(arr.max())
print(arr.argmax())
print(arr.min())
print(arr.argmin())

49
4
2
5


## Shape

Shape is an attribute that arrays have (not a method):

In [26]:
# Vector
arr.shape

(10,)

In [27]:
# Notice the two sets of brackets
arr.reshape(2,5)

array([[10, 12, 41, 17, 49],
       [ 2, 46,  3, 19, 39]])

In [28]:
arr.reshape(2,5).shape

(2, 5)

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [29]:
arr = np.arange(0,10)

In [30]:
arr + arr # change + with any operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Array Functions

Numpy comes with many [universal array functions] which are essentially just mathematical operations you can use to perform the operation across the array.

In [31]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [33]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])