# NumPy Indexing and Selection

Select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
#Get a value at an index
arr[8]

8

In [4]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [5]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [6]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#Important notes on Slices
slice_of_arr = arr[0:6]
#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
#Change Slice
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Note: the changes also occur in our original array!
Data is not copied, it's a view of the original array! This avoids memory problems!

In [10]:
#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [11]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [13]:
# Getting individual element value
arr_2d[1][0] # or arr_2d[1,0]

20

In [14]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [15]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [16]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order

In [17]:
#Set up matrix
arr2d = np.ones((10,10))
for i in range(len(arr2d)):
    arr2d[i] = arr2d[i]*i

Fancy indexing allows the following

In [18]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [19]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
bool_arr = arr>4

In [23]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])