# NumPy Exercises 

Write the code for the following questions in the space provided and submit the .ipynb files on Nalanda

#### Q 1: Import NumPy as np

In [11]:
import numpy as np

#### Q 2: Create an array of 10 zeros 

In [12]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q 3: Create an array of 10 ones

In [13]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Q 4: Create an array of 10 fives

In [14]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Q 5: Create an array of the integers from 10 to 50

In [15]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q 6: Create an array of all the even integers from 10 to 50

In [16]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Q 7: Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q 8: Create a 3x3 identity matrix

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q 9: Use NumPy to generate a random number between 0 and 1

In [19]:
np.random.rand()

0.11482105512512086

#### Q 10: Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [20]:
np.random.normal(0,1,25)

array([-1.57528355,  1.5798533 , -1.31752921, -0.24167223, -0.26216078,
       -0.84029802, -2.08688694, -1.22171118,  0.48484671, -0.14331671,
        0.71452651,  0.47166359, -0.50894056,  0.57715677, -0.17701846,
        1.42113177, -1.38070753,  1.10719417, -0.38319466, -2.02098418,
        0.54107394, -0.72533507,  1.14198317,  0.11732643, -0.8872277 ])

#### Create the following matrix:

#### Q 11: Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection
Write the code to produce the given outputs using the matrix "mat" 

In [26]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3,4]

20

20

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[0:3,1]

array([ 2,  7, 12])

array([[ 2],
       [ 7],
       [12]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[4,:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [35]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [36]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [37]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [38]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])